config/routes.rb
Zoo::Application.routes.draw do
  resources :animals, :foods

end

app/models/animal.rb
class Animal < ActiveRecord::Base
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  # GET /animals
  # GET /animals.xml
  def index
    @animals = Animal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @animals }
    end
  end

  # GET /animals/1
  # GET /animals/1.xml
  def show
    @animal = Animal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @animal }
    end
  end

  # GET /animals/new
  # GET /animals/new.xml
  def new
    @animal = Animal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @animal }
    end
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
  end

  # POST /animals
  # POST /animals.xml
  def create
    @animal = Animal.new(params[:animal])

    respond_to do |format|
      if @animal.save
        format.html { redirect_to(@animal, :notice => 'Animal was successfully created.') }
        format.xml  { render :xml => @animal, :status => :created, :location => @animal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @animal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /animals/1
  # PUT /animals/1.xml
  def update
    @animal = Animal.find(params[:id])

    respond_to do |format|
      if @animal.update_attributes(params[:animal])
        format.html { redirect_to(@animal, :notice => 'Animal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @animal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.xml
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to(animals_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  #want our vendor to be able to do HTTP GET /foods

    def index
      @foods = Food.all

      respond_to do |format|      
        format.xml  { render :xml => @foods }
        format.json { render :json => @foods}
        format.html 
      end
    end

    
    def show 
      @food = Food.find(params[:id])
      respond_to do |format|      
        format.xml  { render :xml => @food }
        format.json { render :json => @food}
      end
    end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<h1>Listing animals</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @animals.each do |animal| %>
  <tr>
    <td><%= animal.name %></td>
    <td><%= animal.color %></td>
    <td><%= animal.size %></td>
    <td><%= link_to 'Show', animal %></td>
    <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
    <td><%= link_to 'Destroy', animal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @animal.name %>
</p>

<p>
  <b>Color:</b>
  <%= @animal.color %>
</p>

<p>
  <b>Size:</b>
  <%= @animal.size %>
</p>


<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foods.each do |food| %>
  <tr>
    <td><%= food.name %></td>
    <td><%= link_to 'Show', food %></td>
    <td><%= link_to 'Edit', edit_food_path(food) %></td>
    <td><%= link_to 'Destroy', food, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food', new_food_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zoo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>